//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileModel", Namespace="http://schemas.datacontract.org/2004/07/ImageService")]
    public partial class FileModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] ContentField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IImageHandlerService")]
public interface IImageHandlerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/SaveImage", ReplyAction="http://tempuri.org/IImageHandlerService/SaveImageResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IImageHandlerService/SaveImageFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
    void SaveImage(ImageService.FileModel image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/SaveImage", ReplyAction="http://tempuri.org/IImageHandlerService/SaveImageResponse")]
    System.Threading.Tasks.Task SaveImageAsync(ImageService.FileModel image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/GetImageNames", ReplyAction="http://tempuri.org/IImageHandlerService/GetImageNamesResponse")]
    string[] GetImageNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/GetImageNames", ReplyAction="http://tempuri.org/IImageHandlerService/GetImageNamesResponse")]
    System.Threading.Tasks.Task<string[]> GetImageNamesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/GetImage", ReplyAction="http://tempuri.org/IImageHandlerService/GetImageResponse")]
    byte[] GetImage(string imageName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageHandlerService/GetImage", ReplyAction="http://tempuri.org/IImageHandlerService/GetImageResponse")]
    System.Threading.Tasks.Task<byte[]> GetImageAsync(string imageName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IImageHandlerServiceChannel : IImageHandlerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImageHandlerServiceClient : System.ServiceModel.ClientBase<IImageHandlerService>, IImageHandlerService
{
    
    public ImageHandlerServiceClient()
    {
    }
    
    public ImageHandlerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImageHandlerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageHandlerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageHandlerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void SaveImage(ImageService.FileModel image)
    {
        base.Channel.SaveImage(image);
    }
    
    public System.Threading.Tasks.Task SaveImageAsync(ImageService.FileModel image)
    {
        return base.Channel.SaveImageAsync(image);
    }
    
    public string[] GetImageNames()
    {
        return base.Channel.GetImageNames();
    }
    
    public System.Threading.Tasks.Task<string[]> GetImageNamesAsync()
    {
        return base.Channel.GetImageNamesAsync();
    }
    
    public byte[] GetImage(string imageName)
    {
        return base.Channel.GetImage(imageName);
    }
    
    public System.Threading.Tasks.Task<byte[]> GetImageAsync(string imageName)
    {
        return base.Channel.GetImageAsync(imageName);
    }
}
